### ISSUE TITLE
Need documentation

### ISSUE THREAD

**Issue by N3XT0R** [Vheissu/Ci-Smarty#38]
Hello,
at first great work!
But... could you write a full documentation for it ? 
Reverse-Engineering of some methods is not really funny, when anyone should use your library.

Example:
Possible View-Paths:

```
// Store a whole heap of template locations
        $this->_template_locations = array(
            config_item('smarty.theme_path') . $this->_theme_name . '/views/modules/' . $this->_module .'/layouts/',
            config_item('smarty.theme_path') . $this->_theme_name . '/views/modules/' . $this->_module .'/',
            config_item('smarty.theme_path') . $this->_theme_name . '/views/layouts/',
            config_item('smarty.theme_path') . $this->_theme_name . '/views/',
            APPPATH . 'modules/' . $this->_module . '/views/layouts/',
            APPPATH . 'modules/' . $this->_module . '/views/',
            APPPATH . 'views/layouts/',
            APPPATH . 'views/'
        );

        // Will add paths into Smarty for "smarter" inheritance and inclusion
        $this->_add_paths();
```

Second thing is, i can only give you a good reputation for your work. It also seems that the library supports 100% all smarty functions, like blocks, captures and more.

Also is a usage with HMVC and Doctrine as ORM possible.

Great work, but documentation is mhh... worse...

**Comment by Vheissu** [comment]
Still planning on writing some documentation. At the moment it still requires a little code-delving.
