### ISSUE TITLE
I have problem about cache page

### ISSUE THREAD

**Issue by mrminh231189** [Vheissu/Ci-Smarty#41]
My template is detail.tpl
I used as $this->parser->parse("article/detail.tpl",$data);
Data have "title 1" and url example.com/article/1
When i change url to example.com/article/2 (Data have "title 2")
=> Data don't change to "title 2", Data still show "title 1".
Please help me. Thanks

**Comment by Vheissu** [comment]
This is more of a Smarty issue than a library one. The best recommended course of action is to use the nocache helper for sections of data that are dynamic: http://www.smarty.net/docs/en/language.function.nocache.tpl
