### ISSUE TITLE
Please upgrad library for codeigniter 3.0

### ISSUE THREAD

**Issue by Vimal10** [Vheissu/Ci-Smarty#42]
Working fine with old version but Not working with CI3.0

**Comment by awalls** [comment]
Just wondering if there was any plans to upgrade this to CI3?

**Comment by Vheissu** [comment]
Hi Adrian,

I don't see why not. A few people seem to use this library and I definitely
think I should update it. Might try and get an update out in the next week
or so depending on what needs to be done.

Kind regards,

Dwayne Charrington

**Comment by Vheissu** [comment]
Support for 3.0 is now finished. Pull down the latest changes and everything should work.

**Comment by awalls** [comment]
Thanks Dwayne.

**Comment by Vimal10** [comment]
Awsome...My next project now i can start :)
