### ISSUE TITLE
SmartyException : unable to write file

### ISSUE THREAD

**Issue by KlustoR** [Vheissu/Ci-Smarty#44]
I can't get this error to go away, any help plz ? Im on ubuntu linux.

An uncaught Exception was encountered

Type: SmartyException

Message: unable to write file ./templates_c/wrt55215dc18cc9c8_54532485

Filename: /opt/lampp/htdocs/CMS/application/third_party/Smarty/sysplugins/smarty_internal_write_file.php

Line Number: 46

Backtrace:

File: /opt/lampp/htdocs/CMS/application/third_party/Smarty/sysplugins/smarty_internal_template.php
Line: 213
Function: writeFile

File: /opt/lampp/htdocs/CMS/application/third_party/Smarty/sysplugins/smarty_internal_templatebase.php
Line: 155
Function: compileTemplateSource

File: /opt/lampp/htdocs/CMS/application/libraries/MY_Parser.php
Line: 186
Function: fetch

File: /opt/lampp/htdocs/CMS/application/controllers/Smartytest.php
Line: 33
Function: parse

File: /opt/lampp/htdocs/CMS/index.php
Line: 292
Function: require_once

**Comment by KlustoR** [comment]
I created a dir templates_c in my root, and now its working. seems that its not loading the config. cant seem to find any reason why its not working properly

**Comment by Vheissu** [comment]
Are you still having the issue of the config file not loading? Are you getting any specific error messages?

**Comment by KlustoR** [comment]
Yes it still doesnt load, no specific errors after creating that directory. I recon it doesnt load as its still giving me the default compile directory, and none of the config options seem to work.

**Comment by Vheissu** [comment]
I have committed some fixes for this issue (better late than never, right?) which will make the config file load properly again.
