### ISSUE TITLE
/libraries/Smarty.php

### ISSUE THREAD

**Issue by phrakon** [Vheissu/Ci-Smarty#45]
I have CI 3 and had a problem after i copied all of your files to codeigniter application folder.
Something worked but config file was ignored. 

When i used $this->CI->load->library('smarty'); in MY_Parser.php was included original Smarty class instead of CI_Smarty in /libraries/Smarty.php. I copied it into system/libraries and it works well.

**Comment by KlustoR** [comment]
I can confirm this, moving smarty.php from application/libraries to system/libraries fixes the problem i had with the config not loading.

**Comment by fixedlv** [comment]
Same here

**Comment by KlustoR** [comment]
Any update on this issue ? I'd like smarty.php in another location then system directory if possible.

**Comment by awalls** [comment]
Is a fix being planned for this as I am getting the same issue as well on a CI3 install?

**Comment by caiosantossp** [comment]
I changed the name of the class from Smart to CustomSmart and all its references and it worked like a charm.

**Comment by Adslive** [comment]
Rhe solution is simple:

1. rename library Smarty.php to MY_Smarty.php (or whaterver you want)  and the class name CI_Smarty to MY_Smarty.

2. Go to MY_Parser file and find the line with this code $this->load->library( 'smarty'); and rename to $this->load->library('my_smarty', NULL, 'smarty'); or change all $this->smarty for $this->_my_smarty

Is working for me! :)
Cheers.

**Comment by Vheissu** [comment]
Cheers everyone. I have kind of moved on from PHP these days, well Codeigniter. However, considering how many people use this library, I'll keep it up-to-date. I've committed some fixes for these issues. Thanks for being patient.
