### ISSUE TITLE
Unable to load the requested class: Ci_smarty

### ISSUE THREAD

**Issue by oldmf** [Vheissu/Ci-Smarty#50]
Hi !
I got this error message:
(Unable to load the requested class: Ci_smarty)
When i upload my project to server.

If I test in localhost this is work fine !!
Any idea?
What is the problem?

I use CodeIgniter-3.0.3

**Comment by radishj** [comment]
There is a place not to be, I have amended, please refer to https://github.com/radishj/Ci-Smarty

(https://github.com/radishj/Ci-Smarty/blob/master/libraries/MY_Parser.php )(Thirty-sixth line)

If you can help you, please give me a star, thank you
