### ISSUE TITLE
`core/MY_Output.php` error when upgraded smarty to 3.1.30

### ISSUE THREAD

**Issue by mytharcher** [Vheissu/Ci-Smarty#56]
I am using composer to autoload smarty library.

In smarty 3.1.30 the debug method has been changed into instance method rather than static (https://github.com/smarty-php/smarty/commit/6087ac5de0f7b5e6948ddb1e6d1ac0b1acb9948a#diff-3677dac38f0fef0ba3a6d370fe50ced6L192).

So in `core/MY_Output.php` the code should be changed like this with new instance:

``` php
            $CI =& get_instance();
            $smarty_debug = new Smarty_Internal_Debug();
            $smarty_debug->display_debug($CI->smarty, TRUE);
```

**Comment by GeeMies** [comment]
Actually the right way to fix the output for Smarty debug templates is 

```
$CI =& get_instance();
$CI->smarty->_debug->display_debug($CI->smarty, TRUE);
```

If you create new Internal_Debug object here, its template_data will be empty and will not work so it's better to use the same Internal_Debug object that Smarty has initialized from beginning.

**Comment by Vheissu** [comment]
Cheers guys. I've just pushed an update.
